import { describe, expect, it, vi } from "vitest";
import { PetDragController, type DragCompletionMode } from "./pet-drag-controller";

function deferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (reason?: unknown) => void;
  const promise = new Promise<T>((onResolve, onReject) => { resolve = onResolve; reject = onReject; });
  return { promise, resolve, reject };
}

function harness(mode: DragCompletionMode | Promise<DragCompletionMode> = "native") {
  let now = 1_000;
  const directions: Array<"left" | "right" | null> = [];
  const savePosition = vi.fn(async () => undefined);
  const startDrag = vi.fn(() => Promise.resolve(mode));
  const controller = new PetDragController({
    startDrag,
    setDragging: (direction) => directions.push(direction),
    savePosition,
    now: () => now,
  });
  return { controller, directions, savePosition, startDrag, advance: (ms: number) => { now += ms; } };
}

describe("PetDragController", () => {
  it("starts once and ignores repeated movement in the same direction", async () => {
    const { controller, directions, startDrag } = harness();
    controller.pointerDown({ x: 0, y: 0 });
    controller.pointerMove({ x: 6, y: 0 });
    await Promise.resolve();
    for (let x = 10; x <= 100; x += 2) controller.windowMoved(x);
    expect(startDrag).toHaveBeenCalledTimes(1);
    expect(directions).toEqual(["right"]);
  });

  it("changes direction only after meaningful horizontal movement", async () => {
    const { controller, directions } = harness();
    controller.pointerDown({ x: 0, y: 0 });
    controller.pointerMove({ x: 6, y: 10 });
    await Promise.resolve();
    controller.windowMoved(100);
    controller.windowMoved(100);
    controller.windowMoved(99);
    controller.windowMoved(98);
    expect(directions).toEqual(["right", "left"]);
  });

  it("lets only the matching native event finish a Windows drag", async () => {
    const { controller, directions, savePosition } = harness("native");
    controller.pointerDown({ x: 0, y: 0 });
    controller.pointerMove({ x: 6, y: 0 });
    const dragId = 1;
    await Promise.resolve();
    controller.pointerReleased();
    controller.nativeEnded({ dragId: 999 });
    expect(controller.stateKind()).toBe("active");
    controller.nativeEnded({ dragId });
    expect(controller.stateKind()).toBe("idle");
    expect(directions).toEqual(["right", null]);
    expect(savePosition).toHaveBeenCalledTimes(1);
  });

  it("finishes a webview drag even if release arrives before start resolves", async () => {
    const start = deferred<DragCompletionMode>();
    const { controller, directions } = harness(start.promise);
    controller.pointerDown({ x: 0, y: 0 });
    controller.pointerMove({ x: 6, y: 0 });
    controller.pointerReleased();
    expect(controller.stateKind()).toBe("active");
    start.resolve("webview");
    await start.promise;
    await Promise.resolve();
    expect(controller.stateKind()).toBe("idle");
    expect(directions).toEqual(["right", null]);
  });

  it("recovers from native start failure", async () => {
    const start = deferred<DragCompletionMode>();
    const { controller, directions, savePosition } = harness(start.promise);
    controller.pointerDown({ x: 0, y: 0 });
    controller.pointerMove({ x: 6, y: 0 });
    start.reject(new Error("failed"));
    await start.promise.catch(() => undefined);
    await Promise.resolve();
    expect(controller.stateKind()).toBe("idle");
    expect(directions).toEqual(["right", null]);
    expect(savePosition).toHaveBeenCalledTimes(1);
  });

  it("suppresses only the click generated by a completed drag", async () => {
    const { controller, advance } = harness();
    controller.pointerDown({ x: 0, y: 0 });
    controller.pointerMove({ x: 6, y: 0 });
    await Promise.resolve();
    controller.nativeEnded({ dragId: 1 });
    expect(controller.shouldSuppressClick()).toBe(true);
    advance(181);
    expect(controller.shouldSuppressClick()).toBe(false);
  });
});
